### ISSUE TITLE
Fix unstable E2E test

### ISSUE THREAD

**Issue by kirill-sizov** [cvat-ai/cvat-opencv#17]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
Test case `actions_tasks/issue_2473_import_annotations_frames_dots_in_name.js` fails from time to time. Need to fix such unstable behavior.

Logs:

<details>
Running:  actions_tasks/issue_2473_import_annotations_frames_dots_in_name.js(19 of 23)
  Import annotations for frames with dots in name.
    Testing case "2473"
  1) Save job. Dump annotation to YOLO format. Remove annotation. Save job.
  2) Upload annotation with YOLO format to job.
  3) "after all" hook for "Upload annotation with YOLO format to job."
Cannot find coverage file /home/runner/work/cvat/cvat/tests/.nyc_output/out.json
Skipping coverage report
 0 passing (1m)
  3 failing
  1) Import annotations for frames with dots in name.
       Testing case "2473"
         Save job. Dump annotation to YOLO format. Remove annotation. Save job.:
     AssertionError: Timed out retrying after 25000ms: Expected to find content: 'YOLO' within the element: <div.rc-virtual-list-holder> and with the selector: '.cvat-modal-export-option-item' but never did.
      at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/actions_tasks/issue_2473_import_annotations_frames_dots_in_name.js:165:65)
  2) Import annotations for frames with dots in name.
       Testing case "2473"
         Upload annotation with YOLO format to job.:
     CypressError: Timed out retrying after 25050ms: `cy.click()` failed because this element:
`<button type="button" class="ant-btn ant-btn-link ant-dropdown-trigger cvat-annotation-header-button">...</button>`
is being covered by another element:
`<div tabindex="-1" class="ant-modal-wrap" role="dialog" aria-labelledby="rcDialogTitle1">...</div>`
Fix this problem, or use {force: true} to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureDescendents (http://localhost:8080/__cypress/runner/cypress_runner.js:168905:78)
      at ensureDescendents (http://localhost:8080/__cypress/runner/cypress_runner.js:154402:8)
      at ensureDescendentsAndScroll (http://localhost:8080/__cypress/runner/cypress_runner.js:154409:14)
      at ensureElIsNotCovered (http://localhost:8080/__cypress/runner/cypress_runner.js:154541:5)
      at runAllChecks (http://localhost:8080/__cypress/runner/cypress_runner.js:154731:52)
      at retryActionability (http://localhost:8080/__cypress/runner/cypress_runner.js:154755:16)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:13022:23)
      at Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:10296:29)
      at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:173835:65)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:173290:14
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:13022:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:10957:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:11014:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:11059:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:11139:18)
      at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:11083:18)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:1457:57)
  3) Import annotations for frames with dots in name.
       Testing case "2473"
         "after all" hook for "Upload annotation with YOLO format to job.":
     CypressError: `cy.parents()` failed because it requires a DOM element.
The subject received was:
  > `undefined`
The previous command that ran was:
  > `cy.contains()`
All 2 subject validations failed on this subject.
Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Import annotations for fram...`
      at ensureElement (http://localhost:8080/__cypress/runner/cypress_runner.js:168779:76)
      at validateType (http://localhost:8080/__cypress/runner/cypress_runner.js:1[686](https://github.com/cvat-ai/cvat/runs/7466121853?check_suite_focus=true#step:11:687)02:16)
      at $Cy.ensureSubjectByType (http://localhost:8080/__cypress/runner/cypress_runner.js:168638:9)
      at $Cy.pushSubjectAndValidate (http://localhost:8080/__cypress/runner/cypress_runner.js:178952:12)
      at Context.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:178436:19)
  From Your Spec
</details>

**Comment by AlexeyAlexeevXperienceAI** [comment]
Test case `tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js` also fails from time to time.
